S07_Activity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django_practice/', include('django_practice.urls')),
    path("admin/", admin.site.urls),
]

django_practice/urls.py
from django.urls import path
from . import views

app_name = "todolist"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:todoitem_id>/", views.todoitem, name="viewtodoitem"),
    path("event/<int:event_id>/", views.event, name="viewevent"),
    # /todolist/register
    path("register", views.register, name="register"),
    path("change_password", views.change_password, name="change_password"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("add_task", views.add_task, name="add_task"),
    path("add_event", views.add_event, name="add_event"),
    path("<int:todoitem_id>/", views.todoitem, name="viewtodoitem"),
    path("<int:todoitem_id>/edit", views.update_task, name="update_task"),
    path("<int:todoitem_id>/delete", views.delete_task, name="delete_task"),
]

django_practice/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ToDoItem(models.Model):
    item_name = models.CharField(max_length=50)
    category = models.CharField(max_length=200)
    status = models.CharField(max_length=50, default="pending")
    date_created = models.DateTimeField("date created")
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="")


class Event(models.Model):
    event_name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    status = models.CharField(max_length=50, default="pending")
    event_date = models.DateTimeField("date created")
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, default="")

django_practice/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label="Username", max_length=20)
    password = forms.CharField(label="Password", max_length=20)


class UpdateUserForm(forms.Form):
    first_name = forms.CharField(label="First Name", max_length=50)
    last_name = forms.CharField(label="Last Name", max_length=50)
    password = forms.CharField(label="Password", max_length=50)


class AddTaskForm(forms.Form):
    task_name = forms.CharField(label="Task Name", max_length=50)
    description = forms.CharField(label="Description", max_length=200)


class AddEventForm(forms.Form):
    event_name = forms.CharField(label="Event Name", max_length=50)
    description = forms.CharField(label="Description", max_length=200)


class UpdateTaskForm(forms.Form):
    task_name = forms.CharField(label="Task Name", max_length=50)
    description = forms.CharField(label="Description", max_length=200)
    status = forms.CharField(label="Status", max_length=50)


class RegisterForm(forms.Form):
    username = forms.CharField(label="Username", max_length=20)
    first_name = forms.CharField(label="First Name", max_length=20)
    last_name = forms.CharField(label="Last Name", max_length=20)
    email = forms.CharField(label="Email", max_length=20)
    password = forms.CharField(label="Password", max_length=20)
    confirm_password = forms.CharField(label="Confirm Password", max_length=20)

django_practice/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone
from django.contrib.auth.hashers import make_password
from .models import ToDoItem, Event
from .forms import (
    LoginForm,
    AddTaskForm,
    UpdateTaskForm,
    RegisterForm,
    UpdateUserForm,
    AddEventForm,
)


def index(request):
    # todoitem_list = ToDoItem.objects.all()
    todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
    event_list = Event.objects.filter(user_id=request.user.id)
    context = {
        "todoitem_list": todoitem_list,
        "user": request.user,
        "event_list": event_list,
    }
    return render(request, "todolist/index.html", context)


def todoitem(request, todoitem_id):
    # todoitem = model_to_dict(ToDoItem.objects.get(pk=todoitem_id))
    todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
    return render(request, "todolist/todoitem.html", model_to_dict(todoitem))


def event(request, event_id):
    # todoitem = model_to_dict(ToDoItem.objects.get(pk=todoitem_id))
    event = get_object_or_404(Event, pk=event_id)
    return render(request, "todolist/event.html", model_to_dict(event))


# def add_task(request):
#     context = {}
#     if request.method == "POST":
#         form = AddTaskForm(request.POST)
#         if form.is_valid() == False:
#             form = AddTaskForm()
#         else:
#             task_name = form.cleaned_data["task_name"]
#             description = form.cleaned_data["description"]
#             duplicates = ToDoItem.objects.filter(task_name=task_name)


#             if not duplicates:
#                 ToDoItem.objects.create(
#                     task_name=task_name,
#                     description=description,
#                     date_created=timezone.now(),
#                     user_id=request.user.id,
#                 )
#                 return redirect("todolist:index")
#             else:
#                 context = {"error": True}
#     return render(request, "todolist/add_task.html", context)
def register(request):
    # users = User.objects.all()
    is_user_registered = False
    context = {"is_user_registered": is_user_registered}
    form = RegisterForm(request.POST)
    if form.is_valid() == False:
        form = RegisterForm()
    else:
        username = form.cleaned_data["username"]
        first_name = form.cleaned_data["first_name"]
        last_name = form.cleaned_data["last_name"]
        email = form.cleaned_data["email"]
        password = make_password(form.cleaned_data["password"])
        duplicates = User.objects.filter(email=email)
        if not duplicates:
            User.objects.create(
                username=username,
                first_name=first_name,
                last_name=last_name,
                email=email,
                password=password,
            )
            context = {"first_name": first_name, "last_name": last_name}
            # return redirect("todolist:index")
        else:
            is_user_registered = True

        # first_name = form.cleaned_data["first_name"]

    # for indiv_user in users:
    #     if indiv_user.username == "johndoe":
    #         is_user_registered = True
    #         break
    # if not is_user_registered:
    #     user = User()
    #     user.username = "cat"
    #     user.first_name = "hot"
    #     user.last_name = "dog"
    #     user.email = "hotdog@mail.com"
    #     user.set_password("cathotdog")
    #     user.is_staff = False
    #     user.is_active = True
    #     user.save()
    #     context = {"first_name": user.first_name, "last_name": user.last_name}
    return render(request, "todolist/register.html", context)


def change_password(request):
    try:
        user_object = User.objects.filter(pk=request.user.id)
        user = user_object[0]
        context = {
            "first_name": user.first_name,
            "last_name": user.last_name,
        }

        if request.method == "POST":
            form = UpdateUserForm(request.POST)
            if form.is_valid() == False:
                form = UpdateUserForm()

            else:
                first_name = form.cleaned_data["first_name"]
                last_name = form.cleaned_data["last_name"]
                user.first_name = first_name
                user.last_name = last_name
                print(form.cleaned_data["password"])
                if form.cleaned_data["password"] != "":
                    user.password = make_password(form.cleaned_data["password"])
                user.save()
                return redirect("todolist:index")

    except:
        context = {"error": True}

    return render(request, "todolist/change_password.html", context)


def login_view(request):
    context = {}
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid() == False:
            form = LoginForm()
        else:
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            context = {"username": username, "password": password}
            if user is not None:
                login(request, user)
                return redirect("todolist:index")
            else:
                context = {"error": True}
    return render(request, "todolist/login.html", context)


def logout_view(request):
    logout(request)
    return redirect("todolist:index")


def add_task(request):
    context = {}
    if request.method == "POST":
        form = AddTaskForm(request.POST)
        if form.is_valid() == False:
            form = AddTaskForm()
        else:
            task_name = form.cleaned_data["task_name"]
            description = form.cleaned_data["description"]
            duplicates = ToDoItem.objects.filter(item_name=task_name)
            try:
                if not duplicates:
                    ToDoItem.objects.create(
                        item_name=task_name,
                        category=description,
                        date_created=timezone.now(),
                        user=User.objects.get(id=request.user.id),
                    )
                    return redirect("todolist:index")
                else:
                    context = {"error": True}
            except User.DoesNotExist:
                ...

    return render(request, "todolist/add_task.html", context)


def update_task(request, todoitem_id):
    todoitem = ToDoItem.objects.filter(pk=todoitem_id)
    item = todoitem[0]
    context = {
        "user": request.user,
        "todoitem_id": todoitem_id,
        "task_name": item.task_name,
        "description": item.description,
        "status": item.status,
    }

    if request.method == "POST":
        form = UpdateTaskForm(request.POST)
        if form.is_valid() == False:
            form = UpdateTaskForm()

        else:
            task_name = form.cleaned_data["task_name"]
            description = form.cleaned_data["description"]
            status = form.cleaned_data["status"]
            if todoitem:
                item.task_name = task_name
                item.description = description
                item.status = status
                item.save()
                return "todolist:index"
            else:
                context = {"error": True}
    return render(request, "todolist:/update_task.html", context)


def delete_task(request, todoitem_id):
    todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
    return redirect("todolist:index")


def add_event(request):
    context = {}
    if request.method == "POST":
        form = AddEventForm(request.POST)
        if form.is_valid() == False:
            form = AddEventForm()
        else:
            event_name = form.cleaned_data["event_name"]
            description = form.cleaned_data["description"]
            duplicates = Event.objects.filter(event_name=event_name)
            try:
                if not duplicates:
                    Event.objects.create(
                        event_name=event_name,
                        description=description,
                        event_date=timezone.now(),
                        user_id=User.objects.get(id=request.user.id),
                    )
                    return redirect("todolist:index")
                else:
                    context = {"error": True}
            except Event.DoesNotExist:
                ...

    return render(request, "todolist/add_event.html", context)

django_practice/templates/todolist/add_event.html
{%extends 'base.html'%}

{%block title%} Add Task{%endblock%}

{%block content%}
    <div class="container">
        <div class="row">
            {% if error == True %}
                <p class="text-danger">Duplicate event found</p>
            {% elif user.is_anonymous == True%}
                <h1 class="text-center my-3">You are not authorized to access this page.</h1>
                <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
            {% else %}
                <div class="col-6 offset-3">
                    <h1 class="text-center my-3">
                        Add An Event
                    </h1>
                    <form action="{% url 'todolist:add_event'%}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="event_name">Event Name:</label>
                            <input type="text" class="form-control" id="event_name" name="event_name" value="{{event_name}}" maxlength="50" required>
                        </div>
                        <div class="mb-3">
                            <label for="description">Description:</label>
                            <textarea class="form-control" name="description" required>{{description}}</textarea>
                        </div>
                        <div class="text-center">
                            <input type="submit" class="btn btn-success" value="Add Event">
                        </div>
                    </form>
                </div>
            {% endif %}
            
        </div>
    </div>
{%endblock%}

django_practice/templates/todolist/add_task.html
{%extends 'base.html'%}

{%block title%} Add Task{%endblock%}

{%block content%}
    <div class="container">
        <div class="row">
            {% if error == True %}
                <p class="text-danger">Duplicate task found</p>
            {% elif user.is_anonymous == True%}
                <h1 class="text-center my-3">You are not authorized to access this page.</h1>
                <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
            {% else %}
                <div class="col-6 offset-3">
                    <h1 class="text-center my-3">
                        Add A Task
                    </h1>
                    <form action="{% url 'todolist:add_task'%}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="task_name">Task Name:</label>
                            <input type="text" class="form-control" id="task_name" name="task_name" value="{{task_name}}" maxlength="50" required>
                        </div>
                        <div class="mb-3">
                            <label for="description">Description:</label>
                            <textarea class="form-control" name="description" required>{{description}}</textarea>
                        </div>
                        <div class="text-center">
                            <input type="submit" class="btn btn-success" value="Add Task">
                        </div>
                    </form>
                </div>
            {% endif %}
            
        </div>
    </div>
{%endblock%}

django_practice/templates/todolist/change_password.html
{%extends 'base.html'%} 
{%block title%}Update Profile{%endblock%}
{%block content%} 
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            {% if user.is_anonymous == True%}
                <h1 class="text-center my-3">You are not authorized to access this page.</h1>
                <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
            {% else %}
                <h1 class="text-center my-3">
                    <h1 class="text-center">Update Profile</h1>
                    <form action="{% url 'todolist:change_password'%}" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="first_name">First Name</label>
                            <input type="text" class="form-control" id="first_name" name="first_name" value="{{first_name}}" maxlength="20" required>
                        </div>
                        <div class="mb-3">
                            <label for="last_name">Last Name</label>
                            <input type="text" class="form-control" id="last_name" name="last_name" value="{{last_name}}" maxlength="20" required>
                        </div>
                        <div class="mb-3">
                            <label for="password">Password:</label>
                            <input type="password" class="form-control" id="password" name="password" value="{{password}}" maxlength="20">
                        </div>
                        <div class="text-center">
                            <input type="submit" value="Confirm" class="btn btn-success">
                        </div>
                    </form>
                </h1>
            {% endif %}
        </div>
    </div>
</div>
{%endblock%}




{% comment %} {%if is_user_authenticated == False%}
<h1>Invalid User Credentials</h1>
<p>Check if the username and password is correct.</p>

{%else%}
<h1>User Password Successfully Updated</h1>
<p>The password has been successfully updated</p>

{%endif%} {% endcomment %}

django_practice/templates/todolist/event.html
{% extends 'base.html' %}
{% block title %}Events{% endblock %}
{% block content %}
    <div class="text-center my-3">
        <h1>{{task_name}}</h1>
        <h3>Description</h3>
        <p>{{description}}</p>
        <h3>Status</h3>
        <p>{{status}}</p>
        <a href="{% url 'todolist:index' %}">Back to index page.</a>

        <button class="btn btn-primary mx-1 text-decoration-none">
            <a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Back to Events</a>
        </button>
    </div>
{% endblock  %}

django_practice/templates/todolist/index.html
{% extends 'base.html'%} 
{% block title %} Home {% endblock %} 
  {% block content %} 
  <h1 class="text-center my-3">
    Welcome {{user.first_name}} {{user.last_name}}!
  </h1>
  <div class="container">
    <div class="row">
      <div class="text-center mb-3"> <h4>My Tasks</h4></div>
    {% if todoitem_list and user.is_anonymous == False%}
      
          <ul class="list-group col-lg-2 offset-lg-5 text-center">
            {% for todoitem in todoitem_list %}
            <li class="list-group-item">
              <a href="{% url 'todolist:viewtodoitem' todoitem.id%}" class="text-decoration-none"
                >{{todoitem.item_name}}</a
              >
            </li>
            {% endfor %}
          </ul>
        
      {% elif user.is_anonymous == True%}
          <h1 class="text-center my-3">You are not authorized to access this page.</h1>
          <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
      {% else %}
        <p class="text-center">No tasks have been created.</p>
      {% endif %}
      <div class="text-center mb-3"> <h4>My Events</h4></div>
      {% if event_list and user.is_anonymous == False %}
        <ul class="list-group col-lg-2 offset-lg-5 text-center">
          {% for event in event_list %}
          <li class="list-group-item">
            <a href="{% url 'todolist:viewevent' event.id%}" class="text-decoration-none"
              >{{event.event_name}}</a
            >
          </li>
          {% endfor %}
        </ul>
      {% elif user.is_anonymous == True%}
        <h1 class="text-center my-3">You are not authorized to access this page.</h1>
        <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
      {% else %}
        <p class="text-center">No events have been created.</p>
    {% endif %}
    </div>
  </div>
   
    {% comment %} {% elif todoitem_list.count == 0 and user%}
      <p>No tasks have been created.</p>
    {% else %}
      <h1 class="text-center my-3">You are not authorized to access this page.</h1>
      <p class="text-center">Kindly login <a href="login">here</a></p>
    {% endif %}  {% endcomment %}
{% endblock %}

django_practice/templates/todolist/login.html
{%extends 'base.html'%} 
{%block title%}Login{%endblock%}
{%block content%} 
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">
                {%if error == True%}
                    <p class="text-danger"> Invalid user credentials, please check your username and password</p>
                {%endif%}
                <h1 class="text-center">Login</h1>
                <form action="{% url 'todolist:login'%}" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username">Username:</label>
                        <input type="text" class="form-control" id="username" name="username" value="{{username}}" maxlength="20" required>
                    </div>
                    <div class="mb-3">
                        <label for="password">Password:</label>
                        <input type="password" class="form-control" id="password" name="password" value="{{password}}" maxlength="20" required>
                    </div>
                    <div class="text-center">
                        <input type="submit" value="Login" class="btn btn-success">
                    </div>
                </form>
            </h1>
        </div>
    </div>
</div>
{%endblock%}
















{% comment %} {%if
is_user_authenticated == False%}
<h1>Something went Wrong</h1>
<p>Please contact your administrator or reset your password</p>
<a href="{% url 'todolist:index' %}">Back to index page</a>
{%endif%} {% endcomment %}

django_practice/templates/todolist/register.html
{%extends 'base.html'%} 
{%block title%}Register{%endblock%}
{%block content%} 
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">
                {%if error == True%}
                    <p class="text-danger"> Invalid user credentials, please check your username and password</p>
                {%endif%}
                <h1 class="text-center">Register</h1>
                <form action="{% url 'todolist:register'%}" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username">Username:</label>
                        <input type="text" class="form-control" id="username" name="username" value="{{username}}" maxlength="20" required>
                    </div>
                    <div class="mb-3">
                        <label for="first_name">First Name:</label>
                        <input type="text" class="form-control" id="first_name" name="first_name" value="{{first_name}}" maxlength="20" required>
                    </div>
                    <div class="mb-3">
                      <label for="last_name">Last Name:</label>
                      <input type="text" class="form-control" id="last_name" name="last_name" value="{{last_name}}" maxlength="20" required>
                  </div>
                  <div class="mb-3">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" name="email" value="{{email}}" maxlength="20" required>
                </div>
                <div class="mb-3">
                  <label for="password">Password:</label>
                  <input type="password" class="form-control" id="password" name="password" value="{{password}}" maxlength="20" required>
              </div>
              <div class="mb-3">
                <label for="confirm_password">Confirm Password:</label>
                <input type="password" class="form-control" id="confirm_password" name="confirm_password" value="{{confirm_password}}" maxlength="20" required>
            </div>
                    <div class="text-center">
                        <input type="submit" value="Register" class="btn btn-success">
                    </div>
                </form>
            </h1>
        </div>
    </div>
</div>
{%endblock%}
















{% comment %} {%if
is_user_authenticated == False%}
<h1>Something went Wrong</h1>
<p>Please contact your administrator or reset your password</p>
<a href="{% url 'todolist:index' %}">Back to index page</a>
{%endif%} {% endcomment %}

django_practice/templates/todolist/todoitem.html
{% extends 'base.html' %}
{% block title %}Items{% endblock %}
{% block content %}
    <div class="text-center my-3">
        <h1>{{task_name}}</h1>
        <h3>Description</h3>
        <p>{{description}}</p>
        <h3>Status</h3>
        <p>{{status}}</p>
        <a href="{% url 'todolist:index' %}">Back to index page.</a>

        <button class="btn btn-primary mx-1 text-decoration-none">
            <a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Back to Tasks</a>
        </button>
    </div>
{% endblock  %}

django_practice/templates/todolist/update_task.html
{% extends 'base.html' %}
{% block title%}Update Tasks{% endblock  %}
{% block content %}
    {% if user.is_anonymous == False %}
        <div class="container">
            <div class="row">
                <div class="col-6 offset-3">
                    <h1 class="text-center my-3">Update Task</h1>
                    {% if error == True %}
                        <p class="text-danger">
                            Task not found
                        </p>
                    {% endif %}
                    <form action="{% url 'todolist:update_task' todoitem.id %}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="task_name">Task Name:</label>
                            <input type="text" class="form-control" id="task_name" name="task_name" value="{{task_name}}" maxlength="50" required>
                        </div>
                        <div class="mb-3">
                            <label for="description">Description:</label>
                            <textarea class="form-control" name="description" required>{{description}}</textarea>
                        </div>
                        <div class="mb-3">
                            <label for="status">Status:</label>
                            <input type="text" class="form-control" id="status" name="status" value="{{status}}" maxlength="50" required>
                        </div>
                        <div class="text-center">
                            <input type="submit" class="btn btn-success" value="Update Task">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock  %}